Repository Garmon-bozia/flight-ui, pull requests merged in 2019-06, with the labels that each got.

#2 basic ui + external service in preview templates
  .gitignore
  Jenkinsfile
  OWNERS
  OWNERS_ALIASES
  charts/flight-ui/values.yaml
  charts/preview/templates/flight-api-service.yaml
  package-lock.json
  package.json
  public/index.html
  src/components/App.js
  src/components/App.test.js
  src/components/flightService.js
  src/components/flights.js
Labels: approved, lgtm, size/XXL

#4 Fixing issue #3
  src/components/App.js
Labels: approved, lgtm, size/XS

#5 change logo
  OWNERS
  public/favicon.ico
Labels: approved, lgtm, size/XS

#6 padding and margins
  src/components/flightService.js
  src/components/flights.js
Labels: approved, lgtm, size/XS

#7 Flight API URL is passed as an ENV variable
  Dockerfile
  charts/flight-ui/templates/_helpers.tpl
  charts/flight-ui/templates/deployment.yaml
  charts/flight-ui/values.yaml
  charts/preview/templates/flight-api-service.yaml
  charts/preview/values.yaml
  docker-start.sh
  src/components/flightService.js
Labels: approved, lgtm, size/M

#8 externalize ingress configuration
  OWNERS
  charts/flight-ui/templates/_helpers.tpl
  charts/flight-ui/templates/configmap.yaml
  charts/flight-ui/templates/deployment.yaml
  charts/flight-ui/values.yaml
  charts/preview/values.yaml
  docker-start.sh
  src/components/flightService.js
Labels: approved, size/M

#9 full deployment in preview
  charts/preview/requirements.yaml
  charts/preview/values.yaml
Labels: approved, lgtm, size/S

#10 delete feature
  public/index.html
  src/components/flightService.js
Labels: approved, lgtm, size/S

#11 rollback delete feature
  src/components/flightService.js
Labels: approved, size/XS

#12 delete feature
  src/components/flightService.js
Labels: approved, lgtm, size/XS

#14 implement flight delete button
  src/components/flightService.js
Labels: approved, lgtm, size/XS
